// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:426bebcf-2696-4245-bac5-e199ce7a5ef0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_caEtzyjHJ",
    "aws_user_pools_web_client_id": "dcvoqr2l6ibq6hn6rnlt66man"
};


export default awsmobile;
